### PR TITLE
fix : remove invalid rating

### PR DESCRIPTION
**Pull request by thayeylolu**

### CODE REVIEW

**Comment by rrrohit1** [comment]
Please do not merge this PR.

**Review by jo4356 — CHANGES_REQUESTED** [review]
A lot of changes gets deleted/reverted with this merge. Could you check that you pulled the most recent change and merge them?

**Comment by rrrohit1** [comment]
First pull from testing to your branch and then make changes to the ratings option.

**Comment by thayeylolu** [comment]
image
The word cloud doesn’t seem to exist in the rendered html on my end

**Comment by rrrohit1** [comment]
On local it is ok not to render. I would suggest to close this PR **without** merging.
Open a new PR from a new branch out of testing branch. Make your changes in that branch.

**Comment by thayeylolu** [comment]
I think the changes should be fine in this branch @rrrohit1

**Pull request merged**
